### ISSUE TITLE
Migrate Hatfield.EnviroData.DataImport to Hatfield.EnviroData.DataAquisition

### ISSUE THREAD

**Issue by jsuwala** [HatfieldConsultants/Hatfield.DataImport#9]
This repository should be migrated to the existing Hatfield.EnviroData.DataAquisition repository. Once this has been done, the Hatfield.EnviroData.DataImport repository should be shut down.

**Comment by gvassas** [comment]
This issue was moved to HatfieldConsultants/Hatfield.EnviroData.DataAcquisition#7
